server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://user-angular-spring.cvkhb6jklkda.eu-west-1.rds.amazonaws.com:3306/userangularspring
    username: rootcloud
    password: rootcloud
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true